### PR TITLE
Update git instructions

### LINKED ISSUE #42: Clarify that a "classic" token is needed for github
The token generation instructions, as written now, assume creation of a classic token. Make this clear so students do not get confused by trying to create a find-grained token, which is the newer best practice suggested by Github.

Classic tokens are created in https://github.com/settings/tokens. Whereas, the fine-grain tokens are generated at https://github.com/settings/tokens?type=beta. 

The page in the summer school repository to modify is <https://arm-development.github.io/arm-summer-school-2024/preliminary/checklist/git.html>.

### PR DESCRIPTION
**Pull request by mgrover1**
Update the git instructions to reflect new github tokens \

Closes #42

### CODE REVIEW

**Comment by mgrover1** [comment]
@wgustafson - can you give this a read over to make sure it addresses the issue?

**Comment by wgustafson** [comment]
@mgrover1 , I was not able to get the fine-grain tokens to work when I tried yesterday. I could only get the classic tokens to permit me to push changes back to the cloud version of the repository. Some of the confusion might be in the instructions to select **repo**, **admin:org**, and **workflow** for the permissions tied to the token. This is a classic mindset, and I think the fine-grain ones work differently? I don't know the details enough to say.

The easy way out is to change the instructions to have folks use classic instead of fine-grain. You edit directs folks to fine-grain. If I just missed something, then fine-grain may work, but the instructions will need to be modified to whatever is needed to make it work.

**Comment by mgrover1** [comment]
Ahhh okay - I thought you were suggesting to use fine-grain instead of the classic one! I can change to the general one.

**Comment by mgrover1** [comment]
@wgustafson this should clarify it more!

Also, @jrobrien91 - this fixes the incorrect repo name as well.

**Pull request merged**
